### ISSUE TITLE
Proofreading mistake

### ISSUE THREAD

**Issue by CHARBEL0088** [cmps253/CMPS253_SPRING_2021_22#10]
In the non-discrimination university policies, there are many times the term "University" takes an apostrophe, and in this case the apostrophe is being used incorrectly.
Indeed, we cannot add apostrophe to (inanimate or nonhuman being nouns) unless we write in an informal way or speak in an informal matter.
For instance: wanna (informally used) but formally "want to" is correct.
In short, the apostrophe here is understandable and could be correct but it is better to cross it out.

**Comment by mahmoudbdeir** [comment]
canned statement to include in syllabus
