### ISSUE TITLE
Overlap between the page index and end of the page reference

### ISSUE THREAD

**Issue by louaibouzaher** [cmps253/CMPS253_SPRING_2021_22#14]
In the second page, the line indicating the beginning of the refenrece "CMPS 253 Syllabus..." and the page index "2" overlap. As shown here:
![image](https://user-images.githubusercontent.com/58881632/150681577-ecf5878e-0bf6-4519-81b5-8c33c2d4a737.png)

**Comment by mahmoudbdeir** [comment]
duplicate, see issue #1
