### ISSUE TITLE
Missing Information in Electronic Resources Section

### ISSUE THREAD

**Issue by chels02** [cmps253/CMPS253_SPRING_2021_22#6]
The section on Electronic Resources (under **Textbook** heading) states that the material will be posted on Moodle and on Slack while, in fact, they will mostly be posted on Professor Bdeir's CMPS 253 site. The link for the website is not provided either. Since the majority of the course will be given online, links to the Webex meetings must also be provided. 
- Christina

**Comment by mahmoudbdeir** [comment]
Invalid, some links will be provided on Moodle (assignments, etc.), and Slack.
